// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// deflex_urgent
SEXP deflex_urgent(Rcpp::Function objective, Rcpp::Function termination, Rcpp::NumericMatrix population, Rcpp::NumericVector upper, Rcpp::NumericVector lower, double CR, double F, int x, int y, int z, Rcpp::Function custom, double B);
RcppExport SEXP deflex_deflex_urgent(SEXP objectiveSEXP, SEXP terminationSEXP, SEXP populationSEXP, SEXP upperSEXP, SEXP lowerSEXP, SEXP CRSEXP, SEXP FSEXP, SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP customSEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::Function >::type objective(objectiveSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type termination(terminationSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type population(populationSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double >::type CR(CRSEXP);
    Rcpp::traits::input_parameter< double >::type F(FSEXP);
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type z(zSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type custom(customSEXP);
    Rcpp::traits::input_parameter< double >::type B(BSEXP);
    __result = Rcpp::wrap(deflex_urgent(objective, termination, population, upper, lower, CR, F, x, y, z, custom, B));
    return __result;
END_RCPP
}
