// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// deflex_strategy3
SEXP deflex_strategy3(Rcpp::Function objective, Rcpp::NumericVector lower, Rcpp::NumericVector upper, Rcpp::NumericMatrix initpop, int iterations, double cr, double f, double c, double jf, bool bounceBack, double precision);
RcppExport SEXP deflex_deflex_strategy3(SEXP objectiveSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP initpopSEXP, SEXP iterationsSEXP, SEXP crSEXP, SEXP fSEXP, SEXP cSEXP, SEXP jfSEXP, SEXP bounceBackSEXP, SEXP precisionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Function >::type objective(objectiveSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type initpop(initpopSEXP);
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< double >::type cr(crSEXP);
    Rcpp::traits::input_parameter< double >::type f(fSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    Rcpp::traits::input_parameter< double >::type jf(jfSEXP);
    Rcpp::traits::input_parameter< bool >::type bounceBack(bounceBackSEXP);
    Rcpp::traits::input_parameter< double >::type precision(precisionSEXP);
    rcpp_result_gen = Rcpp::wrap(deflex_strategy3(objective, lower, upper, initpop, iterations, cr, f, c, jf, bounceBack, precision));
    return rcpp_result_gen;
END_RCPP
}
