# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

deflex_urgent <- function(objective, termination, population, upper, lower, CR, F, x, y, z) {
    .Call('deflex_deflex_urgent', PACKAGE = 'deflex', objective, termination, population, upper, lower, CR, F, x, y, z)
}

