# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

deflex_strategy3 <- function(objective, lower, upper, initpop, iterations, cr, f, c, jf, bounceBack, precision) {
    .Call('deflex_deflex_strategy3', PACKAGE = 'deflex', objective, lower, upper, initpop, iterations, cr, f, c, jf, bounceBack, precision)
}

